apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
spec:
  ingresses:
    - https://sykepenger-im-lps-api.dev-gcp.nav.cloud.nais.io
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi