apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
spec:
  ingresses:
    - https://sykepenger-im-lps-api.dev-gcp.nav.cloud.nais.io
    - https://sykepenger-im-lps-api.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          delegationSource: altinn
          enabled: true
          product: sykepenger
          separator: ":"
          name: inntektsmelding.lps.read
      consumes:
        - name: "nav:sykepenger:inntektsmelding.lps.read"
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
