apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: nav-dev
  ingresses:
    - https://sykepenger-im-lps-api.dev-gcp.nav.cloud.nais.io
    - https://sykepenger-im-lps-api.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          delegationSource: altinn
          enabled: true
          product: inntektsmelding
          separator: "/"
          name: lps.write
      consumes:
        - name: "nav:inntektsmelding/lps.write"
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: hag-lps
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 768Mi
