apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: sykepenger-im-lps-api
  namespace: helsearbeidsgiver
spec:
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      memory: "1024Mi"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  ingresses:
    - https://sykepenger-im-lps-api.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          enabled: true
          product: helse
          separator: "/"
          name: im.read
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: hag-lps

  env:
    - name: EKSPONERT_MASKINPORTEN_SCOPES
      value: "nav:helse/im.read"
