openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Localhost
  - url: https://sykepenger-im-lps-api.dev-gcp.nav.cloud.nais.io
    description: Dev
  - url: https://sykepenger-im-lps-api.ekstern.dev.nav.no
    description: Dev Ekstern
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /forespoersler:
    get:
      summary: Returns a list of forespørsler.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of forespørsel
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
