services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
    environment:
      JSON_CONFIG: '{
          "tokenCallbacks": [
              {
                  "issuerId": "maskinporten",
                  "tokenExpiry": 120,
                  "requestMappings": [
                      {
                          "requestParam": "scope",
                          "match": "nav:inntektsmelding/lps.write",
                          "claims": {
                              "supplier" : {
                                "authority" : "iso6523-actorid-upis",
                                "ID" : "0192:991825827"
                              },
                             "consumer" : {
                                "authority" : "iso6523-actorid-upis",
                                "ID" : "0192:910753614"
                              },
                              "scope": "aud-localhost, nav:inntektsmelding/lps.write",
                              "sub": "testid",
                              "aud": "nav:inntektsmelding/lps.write"
                          }
                      }
                  ]
              }        
          ]
      }'
    ports:
      - 33445:8080


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  broker-kafka:
    driver: bridge