#!/bin/bash

# Get list of staged files
files=$(git diff --cached --name-only --diff-filter=ACM)

# Flag to track if we found any potential tokens
found_token=false

# Loop through each staged file
for file in $files; do
  # Skip the pre-commit hook itself
  if [[ "$file" == *"pre-commit"* ]]; then
    continue
  fi

    # Look for the substring "eyJ" (ignore deleted files) and get the matching lines
    # Get line number
    line=$(grep -ns eyJ "$file")
    line_number=$(echo "$line" | cut -d: -f1)
    if [[ "$line_number" > 0 ]]; then
        line_content=$(echo "$line" | cut -d: -f2-)
        # Print error message in bold red text with the line content
        echo -e "\033[1;31mFant mulig token i $file (linje $line_number):\033[0m"
        echo -e "\033[1;31m$line_content\033[0m"
        echo -e "\033[1;31mSlett denne for å gjennomføre commit\033[0m"
        echo ""
        found_token=true
    fi
done

# If we found any tokens, exit with a non-zero status to prevent the commit
if [ "$found_token" = true ]; then
  exit 1
fi

# If no tokens were found, allow the commit to proceed
exit 0
